dist: trusty
sudo: required
language: cpp
compiler: clang

before_script:
- sudo apt-get update -qq

script:
  # Install Boost Test Framework 1.54
- sudo apt-get install -y -qq libboost-test1.54-dev
- cmake -DCMAKE_BUILD_TYPE=Release .
- cmake --build .
- cmake --build . --target test
- cmake --build . --target package
deploy:
  provider: script
  skip_cleanup: true
  script:
  - curl -T ipfilter-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -uithamsteri:$BINTRAY_API_KEY "https://api.bintray.com/content/hamsterisoft/apt-repo/ip_filter/0.0.$TRAVIS_BUILD_NUMBER/pool/main/i/ip_filter-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"
